name: Test Project

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:16.14.0
    steps:
      - uses: actions/checkout@v3
        width:
          node-version: 16.14.0
      - run: npm ci
      - run: npm test
      - run: npm build
